apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
  namespace: alouter-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: alouter-worker
          image: aunanawat/alouter-worker
          envFrom:
            - secretRef:
                name: mongodb-credential
            - secretRef:
                name: rabbitmq-credential
          volumeMounts:
            - name: router-logs
              mountPath: /worker/router_logs
      volumes:
      - name: router-logs
        persistentVolumeClaim:
          claimName: nfs-pvc
      restartPolicy: Always